### ISSUE TITLE
Add block for main

### ISSUE THREAD

**Issue by Aavild** [JakobTopholt/P4-Unitino#63]
We shouldn't be able to merge or commit to main. Only Pull Requests passing the [.NET Core Desktop action](https://github.com/JakobTopholt/P4-Unitino/actions/workflows/dotnet-desktop.yml) should be able to merge

**Comment by JakobTopholt** [comment]
Burde være gjort nu

**Comment by Aavild** [comment]
Tested and it works perfect :)
